# fly.toml file generated for news-scraper-backend on 2021-12-17T14:44:48+01:00

app = "news-scraper-backend"

kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[build]
  builder = "heroku/buildpacks:20"

[deploy]
  strategy = "immediate"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

  [[services.ports]]
    handlers = ["http"]
    port = "80"
